[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"